apiVersion: batch/v1
kind: Job
metadata:
  name: secret-job
  namespace: zen
  labels:
    app: secret-job
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 480
  template:
    metadata:
      labels:
        app: secret-job
    spec:
      restartPolicy: Never
      containers:
      - name: create-secret
        image: fanzhan1/opencontent-init-container:1.0.59
        imagePullPolicy: Never
        command: ["/bin/bash","-c","/opencontent/init.sh"]
        #securityContext:
          #privileged: true
        volumeMounts:
        - name: secret-generation-config
          mountPath: /opencontent
        - name: certs-volume
          mountPath: /certs
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      volumes:
      - name: secret-generation-config
        configMap:
          name: secret-configmap
          defaultMode: 0777
      - name: certs-volume
        hostPath:
          path: "/install/tls/genCerts/certs"
      nodeSelector:
        labelName: node3
